// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void pulse_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_screen4
void ui_screen4_screen_init(void);
extern lv_obj_t * ui_screen4;
extern lv_obj_t * ui_image4;
extern lv_obj_t * ui_image5;
extern lv_obj_t * ui____initial_actions0;


extern const char * ui_img_background_png;  // assets/BAckground.png
extern const char * ui_img_reisinger_r_png;  // assets/Reisinger_R.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
