// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


// IMAGE DATA: assets/BAckground.png
const char * ui_img_background_png = "S:assets/BAckground.png";
